name: release

on:
    release:
        types: [created]

jobs:
    release-windows-amd64:
        name: build windows/amd64
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@main
            - name: Build
              run: go1.19 build -ldflags -H=windowsgui
            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: soundbrick.exe
                  tag: ${{ github.ref }}
