name: release

on:
    push:

jobs:
    release-windows-amd64:
        name: release windows/amd64
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: wangyoucao577/go-release-action@v1.32
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  goos: windows
                  goarch: amd64
                  ldflags: -H=windowsgui
